name = "cloudflare-share"
compatibility_date = "2024-12-07"
compatibility_flags = ["nodejs_compat"]

account_id = "1bbdd525198a721c33167bbe86fba8ed"
main = "src/index.ts"
workers_dev = false

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://share.mouren.eu.org"

[site]
bucket = "./static/dist"

# 如果不使用自定义域名，将下面的代码注释掉
[[routes]]
pattern = "share.mouren.eu.org"
custom_domain = true

#[[r2_buckets]]
#binding = 'BUCKET'
#bucket_name = 'share'

[[d1_databases]]
binding = "DB"
database_name = "share"
database_id = "d0fc14a1-df6b-4200-98ae-68ddf8db3ef5"
