name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "516d0a360ccdea88dd79e9cf5d2bc3aa"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "as.al", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "85ce3453c9f942a6900a5e9e4cdd34e7" },
  { binding = "PBIMGS", id ="2716bc3deb2744f695f06e5d61e6cfc5" }
]

[site]
bucket = "./static/dist"
